# Generated by Django 6.0 on 2025-12-10 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_mgmt', '0005_alter_enrollment_student'),
        ('student_mgmt', '0002_student_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_mgmt.student'),
        ),
    ]
