# Generated by Django 6.0 on 2025-12-11 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_mgmt', '0007_alter_enrollment_student'),
        ('student_mgmt', '0002_student_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
