# Generated by Django 6.0 on 2025-12-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_studentprofile_roll_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='roll_number',
            field=models.CharField(max_length=50),
        ),
    ]
